hybridgroup/gocv

README.md, env.sh, setupvars_linux.sh, setupvars_osx.sh
This reduces the different flows users have to follow based on their OS.
Remove the +x bit on the script, since it is not meant to be executed but
sourced. Remove the shebang for the same reason.
=> Merge setup_vars_*.sh into env.sh

imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
This one adds support for `cv::resize`. I left off a couple of values from the `InterpolationFlags` enum for now since they are only used in other geometric transformations.
=> Add Resize.

version.cpp
ostringstream.str() returns a temporary string object that's destroyed at the end of the function.
return the macro is just enough.
=> return temp pointer fix

core.cpp, core.go, core.h, core_test.go
This provides access to the Mat data pointer. It is useful for converting OpenCV Mat objects to other image types.
This mirrors the ability to use "tostring()" in the Python bindings. See:
https://stackoverflow.com/questions/5825173/pipe-raw-opencv-images-to-ffmpeg
I've also verified this works with real data by implementing an FFmpeg pipe in my own project.
=> Add Mat ToBytes

README.md
Add sections in the readme that explain compiling gocv to a static library, to make it more easily consumable by projects that don't intend to modify gocv source.  Fixes #59 .
=> in the readme, explain compiling to a static library

env.sh
If you need features not included in the brew install of OpenCV (like GStreamer) and build it yourself, then the env.sh script would not work on Mac. This change, after doing the check to get the brew path, checks if the path was found, if it doesn't return a path, assumes a non-brew install and sets the env variables to the default OpenCV install paths.
=> Support for non-brew installs of opencv on Darwin

imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
Fixes #74. This commit adds cv::arcLength() bindings.
=> Add cv::arcLength() bindings.

core.cpp, core.go, core.h, core_test.go
Noticed the NewMatFromBytes method took in a MatType object but there was no convenient way to save off that information from an existing Mat.
=> core: add Type() method to Mat

env.sh
Some Linux distribution as Fedora need to add PKG_CONFIG_PATH and LD_LIBRARY_PATH to be sure to find libraries at compile time and execution time.
Because opencv is installed in `/usr/local`, we need to fix that paths.
=> Add needed environment variables for Linux

Makefile
We are not all on Ubuntu. So we detect wich tool to use to install dependencies. Note that we must test "dnf" before "yum" because Fedora let "yum" alias to "dnf" with a warning message.
Dependencies are not all found from the Ubuntu list. But on Fedora, that ones seems to be ok. If you found other dependencies, please append them.
=> Add distribution detection to deps rule

core.cpp, core.go, core.h, core_test.go
Two commits (dependent, because unsigned int issue blocked the test for CopyToWithMask()):
* Updated type for Mat.GetUCharAt() and Mat.SetUCharAt() to reflect uint8 instead of int8
* Added Mat.CopyToWithMask() per #47
=> Fixed unsigned int issue and added Mat.CopyToWithMask()

cmd/caffe-classifier/main.go, cmd/faceblur/main.go, cmd/facedetect/main.go, cmd/showimage/main.go, cmd/tf-classifier/main.go
... murphy's law.
let's try to avoid panic situations like #72 . simply, every read or load call must be checked.
weird: the caffe-classifier example fails gracefully, the tf-classifier still panics (given a wrong filename).
=> cmd: check loading resources

core.go, core_test.go, imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
Hi,
I am learning OpenCV (like I started today) and chose your lib to write Go code. I am playing with image manipulation to be able to read content from pictures. I had to apply a perspective transformation, so I've added two new functions to the `gocv` API. I use these functions that way:
``` go
// `corners` is also of type `[]image.Point` and contains the actual corners of the "thing" I am interested in the image.
gridWidth := int(math.Max(widthTop, widthBottom))
gridHeight := int(math.Max(heightLeft, heightRight))
flatCorners := []image.Point{
image.Pt(0, 0),
image.Pt(gridWidth, 0),
image.Pt(gridWidth, gridHeight),
image.Pt(0, gridHeight),
}
m := gocv.GetPerspectiveTransform(corners, flatCorners)
gocv.WarpPerspective(img, img, m, image.Pt(gridWidth, gridHeight))
```
~Because I am not …
=> Add WarpPerspective and GetPerspectiveTransform

imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
This PR adds the `DrawContours()` function.
The test case creates the following image:
It finds the contours of the square and draws them with a larger border:
---
~~This PR works only when disabling CGO checks (`GODEBUG=cgocheck=0`) because I
am passing a struct of structs (slice of slices) and it breaks one of the CGO
"rules" I guess.~~
~~I am not really sure to know how to fix this to be honest, maybe we would need
a different C structure to handle multidimensional arrays of `cv::Point` and
being able to pass such data structures from Go to C. In `FindContours()`, we
have done the opposite and it seems to work, so there must be a way, but I just
don't know what to do here right now.~~
=> Add DrawContours()

core.go
Fix #130
---
I believe `Type()` should return a `MatType` because that's what we use
everywhere else, and it would make comparisons more natural. I stumbled upon
this while reviewing #125.
It could be since as a BC break even though we did not reach version `1.0.0` yet.
=> Mat Type() should return MatType

core.go
Since #134, we can directly compare the `Mat` type so no need to cast it anymore (cf. #125).
=> Compare Mat Type directly

cmd/caffe-classifier/main.go
I wanted to try this demo and the links were outdated.
Maybe we could host these files in a separate repo?
=> Update links in caffe-classifier demo

cmd/README.md, cmd/find-circles/main.go, core.go, core_test.go
This is a proposal to simplify the way we get data from `Mat`, which we use as
a general purpose data structure. I find it more convenient because when
looking on the Internet (for example, for Hough transforms), people talk about
`Vec` or `Vec3f` (and so on), not `Mat`. Of course, a matrix can be used as a
vector, but it is less simple than having an accessor for that.
It is still possible to use the `Mat` and do the maths by yourself, it is only
a nice helper. We could add `GetVecdAt()` for `double`/`float64`, `GetVeciAt()`
for `int`, etc.
=> Add GetVecfAt() and GetVecifAt() functions to Mat

cmd/basic-drawing/main.go, imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
I wanted to reproduce [this tutorial](https://docs.opencv.org/2.4/doc/tutorials/core/basic_geometric_drawing/basic_geometric_drawing.html#drawing-1). Here are the screenshots for the two images created in the newly added example:
=> Add Ellipse() and FillPoly() functions

core.go
CopyMakeBorder currently accepts int in place of borderType. It would be nice if `CopyMakeBorder` accepted `BorderType` instead of `int`. This way the parameter would be more consistent with `OpenCV` and other `gocv` function that accept similar parameters and it would also be user friendlier to developers i.e. more straightforward to understand.
=> Make borderType in CopyMakeBorder be type BorderType

.travis.yml, Makefile, appveyor.yml, cmd/README.md, cmd/img-similarity/main.go, contrib/img_hash.cpp, contrib/img_hash.go, contrib/img_hash.h, contrib/img_hash_test.go, env.cmd, env.sh
I went on a bit of a tangent this evening.
This wraps almost all of the img_hash module. The API is largely equivalent: `ImgHashBase` is an interface with Compute and Compare methods, and each hash has a struct implementing that interface.
Differences are:
* The non-class convenience functions for compute are not implemented, because their names would collide and the lack of an equivalent compare made them sort of pointless.
* Hashes that take parameters have these as public members. To solve the default value problem, those hashes (but inconsistently, only those hashes) have a `NewSomethingHash` function.
* Several functions for BlockHash and RadialVarianceHash aren't implemented because they would require keeping state, which would require adding a `Close()` function or a great deal of …
=> Add contrib/img_hash module

cmd/ssd-facedetect/main.go
Path within example command referred to a previous directory location. Update for current location.
=> Fix example command.

cmd/ssd-facedetect/main.go
Executable name in help text was out of sync with directory name.
=> Fix executable name in help text.

videoio.go, videoio_test.go
New API: CodecString() returns a string representation of FourCC bytes from OpenCV video options.
Closes: #192
=> Feature: CodecString()

core.go, core_test.go
`Rotate()` function accepts an integer rotation code. This however opens a potential "security" hole or rather a buggy situations as a user can submit any integer which will cause the successfully built program to hang.
By introducing `RotateFlag` as per [cv::RotateFlags](https://docs.opencv.org/master/d2/de8/group__core__array.html#ga6f45d55c0b1cc9d97f5353a7c8a7aac2) enum which is passed to [cv::rotate](https://docs.opencv.org/master/d2/de8/group__core__array.html#ga4ad01c0978b0ce64baa246811deeac24) we eliminate this possibility and in turn gain cleaner code and happy programmers :-)
=> Added RotateFlag type

core.h, imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
This adds `CalcHist` function which brings in support for [calcHist](https://docs.opencv.org/3.4.1/d6/dc7/group__imgproc__hist.html#ga6ca1876785483836f72a77ced8ea759a) opencv function to gocv.
I need to add test to it -- I've verified the implementation on some basic examples in one of my personal projects, but I need to come up with a few simple test cases for `gocv`.
=> Added opencv::calcHist implementation

core.cpp, core.go, core.h, core_test.go
@deadprogram It doesn't seem necessary to return an error for the single byte variants. The int8 version probably isn't that useful, but I could imagine a scenario where someone wants to access the raw bytes even if the Mat is of a different type.
Resolves #250
=> Add Mat.DataPtr methods for direct access to OpenCV data

Makefile
The present Makefile has a typo in the (RPMS) package name, for CentOS 7 and Fedora 28.
This PR fixes that, and also addresses the wget problem in #282. :smile:
It also adds `unzip` to the package list for CentOS and Fedora, as that's needed and isn't part of the general base system.
=> Fix package names for CentOS 7 and Fedora 28

cmd/find-circles/main.go
When the image has no circles, the following error is thrown: `runtime error: index out of range` this is because v in https://github.com/hybridgroup/gocv/blob/master/cmd/find-circles/main.go#L62 has length 1 or 0. Adding a lenght check fixes the issue
=> add condition to handle no circle found in circle detection example

README.md
Adding instructions for the pkgconfig installation for macOS.
[#306](https://github.com/hybridgroup/gocv/issues/306)
=> pkgconfig is required for building or running the code examples for macOS

imgcodecs.cpp, imgcodecs.go, imgcodecs.h, imgcodecs_test.go
Usage example
`data, err := gocv.IMEncodeWithParams(".jpg", img, []int{gocv.IMWriteJpegQuality, 95})`
=> Added IMEncodeWithParams function

Makefile
This is my first ever pull request on an open source project so bear with me.
I noticed an issue on a fresh Ubuntu 16.04 64bit machine when trying to use the "make install" command for gocv.  If curl is not installed on the machine, then the installer ends up in a looping state.
Below is the looping output I was seeing prior to this change.
sudo make install
sudo ldconfig
cd -
/bin/sh: 1: cd: can't cd to /tmp/opencv/opencv-3.4.2/build
sudo apt-get -y update
sudo apt-get -y install unzip build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease …
=> Add required curl package to the RPM and DEBS

cmd/hand-gestures/main.go
The process of "cleaning up image" concomitant with the process of "find biggest contour", both with their respective functions and equations, results in data, that are converted into green dots in the image; therefore, these points represent areas, or rather vertices resulting from the equations, which, contrary to what the code shows, aren't the number of fingers. The number of fingers is the number of vertices found plus one, because every 2 large areas with contours(fingers), we have 1 vertex, formed by 2 contours with angle less than 90.
I modified the code and my results turn on a little better. I ask for apologies if I understand wrong. Thank you.
=> Improve accuracy of hand gesture finger count

videoio.cpp, videoio.go, videoio.h, videoio_test.go
When opening a video capture (file or device) `VideoCapture::open(...)` returns `bool` value depending on success of the `open` call. However we are ignoring the return value and not setting the error when returning from Go bindings functions. This leads to bugs in Go programs which are checking for `error` values returned from `VideoCapture*` functions when the returned error is `nil`, which leads to the code assuming the video capture `open` was successful.
Furthermore `VideoCapture::open(...)` calls return `bool` values. We are however returning integer, which is ok in C/C++ world as it's implicitly cast by `cgo` into particular bool value. However, we want to make this explicit in GoCV so we are returning bool now as per OpenCV.
=> Return the right type and error when opening VideoCapture fails

openvino/env.sh
This PR removes `-lopencv_face` from `env.sh` to skip linking openvino binaries with opencv's face contrib module.
=> Removing linking against face contrib module

imgproc.cpp, imgproc.go, imgproc.h, imgproc_test.go
Hi, this PR is for adding the CLAHE that is one of the histogram equalization methods.
Maybe it's none of my business. I've added the official OpenCV link describing the CLAHE for your reference, although this reference's code is written by Python.
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_histograms/py_histogram_equalization/py_histogram_equalization.html?highlight=clahe#clahe-contrast-limited-adaptive-histogram-equalization
As I'm not very familiar with both the OpenCV and gocv, please give me some comments if this PR has some problems, 
Thank you.
=> Implement CLAHE to imgproc

cmd/caffe-classifier/main.go
The caffe-classifier example uses the wrong filename, which might be a bit confusing.
This PR fixes it.
=> Fixing filename in caffe-classifier example

core.cpp, core.go, core.h, core_test.go
The current bitwise operations don't have a parameter for a mask (I needed the mask parameter for a project), so I added new functions with this parameter - BitwiseAndWithMask, BitwiseNotWithMask, BitwiseOrWithMask, and BitwiseXorWithMask. Thanks!
=> Added Bitwise Operations With Masks

ROADMAP.md, dnn.cpp, dnn.go, dnn.h, dnn_test.go
Hi guys, I'm trying to implement the #395 , someone can please review and make suggestions?
=> add BlobFromImages

videoio.go, videoio_test.go
Similarly to `CodecString`, the `ToCodec(codec)` method returns a value that can be used in `VideoCapture.Set`
Example: `vc.Set(gocv.VideoCaptureFOURCC, vc.ToCodec("MJPG"))`
=> Added ToCodec to convert FOURCC string to numeric representation

core.cpp, core.go, core.h, core_test.go
Added the KMeans function.
However, I also realized that I wanted to call the function on a `[]image.Point` to cluster a bunch of contour points and not just a `Mat` type; so my solution was to create a `KMeansPoints` function.
Please let me know if there is a better way to do it and that function isn't required. If it is required, please let me know if you would like to rename it to something better.
=> RFC: Add KMeans function

imgproc_test.go
TestHoughLines in opencv generates a slightly different result for the
TestHoughLines test on arm64 when opencv is built in RELEASE mode
because of differences in rounding.  This is because the
TestHoughLinesStandard code ends up using the fused FMADD instead of
separate FMUL and FADD instructions on arm64 and ends up having
rounding semantics that are different from x86.  x86 does not use
fused FMA instructions in its default build.
Building opencv in DEBUG mode hides this error because the multiply
and add ops don't get fused.  Additionally, a comment in cvRound
function in opencv specifies that calling code must tolerate an error
of +/-1 and given that the function is used in a loop to normalise
multiple values in HoughLines, the error adds up.
Fix up the test case to tolerate …
=> Tolerate imprecision in TestHoughLines

core_test.go
The SolvePoly test TestSolvePoly generates a result that is slightly
imprecise on aarch64 (~2.75e-62) as opposed to a precise result on
x86_64.  This change adjusts the test to tolerate this imprecision.
=> Tolerate imprecise result in SolvePoly

imgproc.go
to solve issue
https://github.com/hybridgroup/gocv/issues/537
=> In FillPoly and DrawContours functions, remove func() wrap to avoid memory freed before calling opencv functions.

imgcodecs.cpp
This PR optimizes the copying of data used for IMDecode method, to improve in-memory only performance.
=> imgcodecs: optimize copy of data used for IMDecode method

dnn.cpp, dnn_test.go
This PR respects the bit depth of the input image to set the expected output when converting an image to a blob. Needed to allow for proper DNN handling of greyscale images.
=> dnn: respect the bit depth of the input image to set the expected output

core.cpp, core.go, core.h
=>  Fix memory leak in Mat.Size() and Mat.Split()

Makefile
The raspberry pi zero uses a different instruction set to the raspberry pi 2 & 3. I have added to the makefile 2 new commands, **build_raspi_zero** and **install_raspi_zero**, for installing on the rpi zero.
=> Added raspberry pi zero support to the makefile

cuda/core.cpp, cuda/core.go, cuda/core.h, cuda/cuda.cpp, cuda/cuda.go, cuda/cuda.h, cuda/imgproc.cpp, cuda/imgproc.go, cuda/imgproc.h, cuda/objdetect.cpp, cuda/objdetect.go, cuda/objdetect.h
1060 using about 40%
DetectMultiScale elapsed ~30 ms
```
package main
import (
"fmt"
"image/color"
"gocv.io/x/gocv"
"gocv.io/x/gocv/cuda"
)
func main() {
deviceID := "0"
webcam, err := gocv.OpenVideoCapture(deviceID)
if err != nil {
fmt.Printf("Error opening video capture device: %v\n", deviceID)
return
}
defer webcam.Close()
window := gocv.NewWindow("Capture Window")
defer window.Close()
img := gocv.NewMat()
defer img.Close()
hog := cuda.CreateHOG()
hog.SetSVMDetector(hog.HOGDefaultPeopleDetector())
gpumat := cuda.NewGpuMat()
defer gpumat.Close()
graygpumat := cuda.NewGpuMat()
defer graygpumat.Close()
fmt.Printf("Start reading device: %v\n", deviceID)
for {
if ok := webcam.Read(&img); !ok {
fmt.Printf("Device closed: %v\n", deviceID)
return
}
if img.Empty() {
continue
} …
```
=> Update cuda api

imgproc.cpp, imgproc.go, imgproc.h
I'm new to both opencv and gocv.
The [OpenCV Threshold(...) function()](https://docs.opencv.org/3.3.0/d7/d1b/group__imgproc__misc.html#gae8a4a146d1ca78c626a53577199e9c57) returns a threshold value for use in later computations (eg. Canny edge detection). The [analogous GoCV function](https://pkg.go.dev/gocv.io/x/gocv?tab=doc#Threshold) operates on the destination Mat, but returns no value.
Hopefully this small change won't break things? I've used the float32 type for the returned value, but if it should be float64 please feel free to change.
Thanks for all your work on this fantastic set of bindings!
Mike Traynor.
=> Threshold() should return a value

imgproc.go
This PR is to ensure we do not free contours data until after we have drawn the needed contours.
=> imgproc: do not free contours data until after we have drawn them

cuda/cuda.go
The path 
`https://github.com/opencv/opencv` does not exist
The relevant path should be?
`https://github.com/opencv/opencv`
=> Wrong documentation [cuda.go]
