env.sh

Update env.sh for Arch Linux

---

videoio.cpp
videoio.go
videoio.h
videoio_test.go

I'm using `gocv` in a project and I've added a few missing bindings. I'm going to attempt to upstream these additions if you're interested.

Add VideoCapture::get

---

core.cpp
core.go
core.h
core_test.go

See
https://docs.opencv.org/3.3.0/d2/de8/group__core__array.html#ga191389f8a0e58180bb13a727782cd461

add cv::mean binding with single argument

---

cmd/saveimage/main.go
core.h
imgcodecs.cpp
imgcodecs.go
imgcodecs.h
imgcodecs_test.go

see
https://docs.opencv.org/3.3.0/d4/da8/group__imgcodecs.html#gabbc7ef1aa2edfaa87772f1202d67e0ce
https://docs.opencv.org/3.3.0/d4/da8/group__imgcodecs.html#ga292d81be8d76901bff7988d18d2b42ac

Add image compression flags for gocv.IMWrite

---

version.cpp
version.h

1. change the return temp string https://github.com/hybridgroup/gocv/pull/21
2. fix the write-strings warning,

fix the write-strings warning

---

README.md

clean, and not cleanup

---

env.sh

Fix to get the OpenCV path with "brew info".

Update env.sh for Homebrew

---

cmd/capwindow/main.go
cmd/counter/main.go
cmd/faceblur/main.go
cmd/facedetect/main.go
cmd/motion-detect/main.go
cmd/pvl/faceblur/main.go
cmd/pvl/smiledetect/main.go
cmd/showimage/main.go

In infinite loop the windows could not be closed by pressing a key.

Fixed closing window in examples in infinite loop

---

env.sh

Fix [#57 Issue](https://github.com/hybridgroup/gocv/issues/57)
This is my first time contribute, and i'm not familiar with git
Please let me know if I made a mistake
Thanks you for making cool lib!

#57 Issue fix

---

imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Add AdaptiveThreshold function

Add adaptive threshold function

---

highgui.go

highgui: fix constant in NewWindow

---

core.cpp
core.go
core.h
core_test.go

This PR adds ToImage() to Mat, so it is easy to convert to Go image.Image .

Add Mat.ToImage()

---

imgproc.go

Fix the hack to convert C arrays to Go slices.

---

videoio.go
videoio_test.go

Check numerical parameters for gocv.VideoWriterFile

---

.travis.yml
core.go
core_test.go
imgcodecs.go
imgcodecs_test.go

Make toByteArray safe for empty byte slices

---

videoio.cpp
videoio.go
videoio.h
videoio_test.go

Add isColor to VideoWriterFile
Closes: #196

Add isColor to VideoWriterFile

---

imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

add HoughLinesPWithParams for this Issues #204

add HoughLinesPWithParams

---

CONTRIBUTING.md

Adds a description of a simple `gocv` contribution guidelines outlined in [231](https://github.com/hybridgroup/gocv/issues/231#issuecomment-402504064)

Added a sample gocv workflow contributing guideline

---

Makefile
ROADMAP.md
core.h
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

MinAreaRect finds a rotated rectangle of the minimum area enclosing the input 2D point set.

MinAreaRect()

---

README.md

Add an undefined variable `deviceID`.

fix a varible error in example code in README

---

README.md
win_build_opencv.cmd

Disabled progress bar for improved download and archive extraction performance.
On fast internet and SSD these changes can save more than two minutes.
Affects: 
- Invoke-WebRequest
- Expand-Archive
Also added extra comments to explain to the user in case of slower Internet connectivity.

Improved download and archive extraction speed during setup

---

CHANGELOG.md
README.md
openvino/README.md
version.go
win_build_opencv.cmd

the script tries to write to c:. if GOPATH is on a different drive, the
script will fail to properly change directories.
Signed-off-by: Mike Lloyd <mike@reboot3times.org>

fixed GOPATH bug.

---

ROADMAP.md
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Hi,
I added the Sobel function as requested on [this issue](https://github.com/hybridgroup/gocv/issues/270) 😃 
Regards

Added Sobel function

---

ROADMAP.md
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Hi,
I added the `SpatialGradient` function as defined on the [ROADMAP](https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md)
Regards

SpatialGradient

---

ROADMAP.md
core.cpp
core.go
core.h
core_test.go

Hi,
I added the `phase` function to `core` and updated the `ROADMAP`
Regards

Added Phase function

---

core.cpp
core.go
core.h
core_test.go

Add sort method for enhancement request #310.

core: add Sort() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add Trace method for enhancement request #312.

core: add Trace() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add SortIdx method for enhancement request #315.

core: add SortIdx() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add Reduce method for enhancement request #318.

core: add Reduce() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add Solve method for enhancement request #322.

core: add Solve() method to Mat

---

ROADMAP.md
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Hi, I added the `SepFilter2D` function 🎃

SepFilter2D

---

core.cpp
core.go
core.h
core_test.go

Add SolveCubic method for enhancement request #326.

core: add SolveCubic() method to Mat

---

ROADMAP.md
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Hi, I added the `fitLine` function. 👾

Added fitLine function

---

core.cpp
core.go
core.h
core_test.go

Add SolvePoly method for enhancement request #331.

core: add SolvePoly() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add Repeat method for enhancement request #335.

core: add Repeat() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add PolarToCart method for enhancement request #337.

core: add PolarToCart() method to Mat

---

core.cpp
core.go
core.h
core_test.go

Add ScaleAdd method for enhancement request #341.

core: add ScaleAdd() method to Mat

---

ROADMAP.md
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Added support for the HoughLinesPointSet function
Fixed up some error strings in multiple test cases.

Added support for the HoughLinesPointSet function

---

imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Hello, this PR is for adding the connected components functions to imageproc. Thanks!

Implement Connected Components Functions

---

dnn.cpp
dnn.go
dnn.h
dnn_test.go

This PR adds missing methods for loading of in-memory deep neural network models. The existing methods only support loading from the filesystem.

Implement dnn methods for loading in-memory models.

---

core.h
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Add opencv's 'MinEnclosingCircle' function to gocv (and test).

---

imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

I added the BoxPoints function because it looks like it isn't implemented yet. Also, the BorderIsolated border type constant, was missing so I added that too.

added BoxPoints function and BorderIsolated const

---

video.cpp
video.go
video.h
video_test.go

Hi guys! this is my first contribution to this project and I wanted to ensure that this code is correct in terms of the contributions guideline. So a little hand holding would be appreciated.
This change simply adds the the ability to change the default options that are set using the default MOG2 & KNN constructor.
Cheers!

Addition of MOG2/KNN constructor with options

---

ROADMAP.md
imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Added function call mapping to cv::morphologyDefaultBorderValue();

Added function call to cv::morphologyDefaultBorderValue

---

Makefile
cmd/cuda/main.go
contrib/cgo.go
cuda/README.md
cuda/cgo.go
cuda/cuda.cpp
cuda/cuda.go
cuda/cuda.h
cuda/cuda_test.go
cuda/cudabgsegm.cpp
cuda/cudabgsegm.go
cuda/cudabgsegm.h
cuda/cudabgsegm_test.go

Initial implementation of cuda core and cudabgsegm with MOG and MOG2 algorithms

initial cuda core and bgsegm implementation

---

core.h
features2d.cpp
features2d.go
features2d.h
features2d_test.go

Needed this functionality, and have started to use it. Open to any and all suggestions!

Add support for SimpleBlobDetectorParams

---

ROADMAP.md
dnn.cpp
dnn.go
dnn.h
dnn_test.go

add ImagesFromBlob

---

imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Add MorphologyExWithParams to allow passing in the number of iterations.

Add MorphologyExWithParams

---

contrib/tracking_test.go
imgproc.go

Fix few places where 'defer' statements were called in a for loop. Calling 'defer' this way can cause a resource leak.

Fix possible resource leak

---

core.cpp
core.go
core.h
core_test.go

The Mean() function does not have the additional parameter for a mask, so I added a separate function MeanWithMask(). Thanks!

added MeanWithMask function for Mats

---

Makefile

added go clean --cache to clean target, see issue 458

---

cmd/showimage/main.go

format: better format

---

cuda/cudawarping.cpp
cuda/cudawarping.go
cuda/cudawarping.h
cuda/cudawarping_test.go

This PR is not ready yet. I have no previous experience of wrapping C/C++ code with Go hence putting this PR out early so that I could receive suggestions and feedback. :baby:

[WIP] Support for CUDA Image Warping

---

cmd/facedetect-from-url/main.go

I deleted the branch of #498 by mistake....
I fixed review point from @deadprogram .
Thanks for the review.

Example: face detection from image url by using IMDecode

---

ROADMAP.md
core.cpp
core.go
core.h
core_test.go

Add SetIdentity method for enhancement request #529

core: add setIdentity() method to Mat

---

imgproc.cpp
imgproc.go
imgproc.h
imgproc_test.go

Add GetRectSubPix

---

ROADMAP.md

Update ROARDMAP.md as scaleAdd has been alrady implemented in #343.

Update ROADMAP.md by removing scaleAdd

---

core.cpp
core.go
core.h
core_test.go
svd.cpp
svd.go
svd.h
svd_test.go

add multiply between matrices(#376) and transpose matrix,
Singular Value Decomposition (SVD), cv::SVD::compute() (#557)

add functions (singular value decomposition, multiply between matrices, transpose matrix)

---

Dockerfile

Dcokerfile ends with CMD, otherwise if we were using RUN and the go program is a infinite loop, then the following instructions either in DockerFile or docker-compose file has no chance to run

Docker file last command change
